# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-21 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('naivebayes', '0002_auto_20170321_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Count',
            new_name='FeatureCount',
        ),
        migrations.RemoveField(
            model_name='element',
            name='categories',
        ),
        migrations.CreateModel(
            name='CategoryCount',
            fields=[
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='naivebayes.Category')),
                ('data_count', models.IntegerField()),
            ],
        ),
    ]
