# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-22 00:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naivebayes', '0004_auto_20170322_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categories',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='feature',
            old_name='features',
            new_name='name',
        ),
    ]
